name: Fix Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  fix-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Gradle 8.13
        run: |
          wget https://services.gradle.org/distributions/gradle-8.13-bin.zip
          unzip gradle-8.13-bin.zip

      - name: Generate new wrapper
        run: |
          ./gradle-8.13/bin/gradle wrapper \
          --gradle-version 8.13 \
          --gradle-distribution-sha256-sum 20f1b1176237254a6fc204d8434196fa11a4cfb387567519c61556e8710aed78

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Fix Gradle Wrapper for F-Droid"
          git push
